// Code generated by statik. DO NOT EDIT.

package web

import (
	"github.com/rakyll/statik/fs"
)


const Web = "web" // static asset namespace

func init() {
	data := "PK\x05\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
		fs.RegisterWithNamespace("web", data)
	}
	