// Code generated by statik. DO NOT EDIT.

package built

import (
	"github.com/rakyll/statik/fs"
)


const Built = "built" // static asset namespace

func init() {
	data := "PK\x05\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
		fs.RegisterWithNamespace("built", data)
	}
	